### ISSUE TITLE
.jadelintrc not being used

### ISSUE THREAD

**Issue by PyroSA** [patwork/gulp-jadelint#3]
We use Jade to build XML files.

Because of that we include the jade-lint config file .jadelintrc containing:
{ "OnlyHTMLDoctype": "ignore" }

This seems to work fine when running jadelint from the command-line, but the gulp task does not seem to honor it.

I've tried putting the .jadelintrc in both my project's root folder, as well as in the folder with the jade itself.

**Comment by patwork** [comment]
ok, I will check this

**Comment by patwork** [comment]
we need to wait until jadelint v0.3

https://github.com/rrdelaney/jadelint/issues/14

**Comment by PyroSA** [comment]
Thanks, didn't have a chance to dig into it.
Also affects our Atom linter plugin, but both should be sorted once jadelint traverses up the path

**Comment by rrdelaney** [comment]
Jadelint v0.3 has been released and now supports config objects.

**Comment by patwork** [comment]
New gulp-jadelint v0.1.0 supports .jadelintrc as well.

**Comment by raftheunis87** [comment]
Is it possible to put the .jadelintrc in another location then the root folder? For most of the linting plugins it is possible to set a config like this:

.pipe(jadeLint({config: paths.jade.lint})))

**Comment by rrdelaney** [comment]
@raftheunis87 

You can use the Jadelint API directly with

``` js
let fs = require('fs')
let jadelint = require('jadelint')
let gutil = require('gulp-utils')
const jadelintrc = 'myJadelintRC'

gulp.src('**/*.jade')
.pipe(jadelint(JSON.parse(fs.readFileSync(jadelintrc)), undefined,(r) => {
  r.report()
  gutil.log(r.log)
})
```

See https://github.com/rrdelaney/jadelint/blob/master/bin/jadelint for more example usage
